//Package po generated by 'freedom new-po'
package po

import (
	"github.com/jinzhu/gorm"
	"time"
)

// DomainEventPublish .
type DomainEventPublish struct {
	changes map[string]interface{}
	ID      int       `gorm:"primary_key;column:id"`
	Topic   string    `gorm:"column:topic"`
	Send    int       `gorm:"column:send"`    // 0未发送，1发送
	Content string    `gorm:"column:content"` // 内容
	Created time.Time `gorm:"column:created"`
	Updated time.Time `gorm:"column:updated"`
}

// TableName .
func (obj *DomainEventPublish) TableName() string {
	return "domain_event_publish"
}

// TakeChanges .
func (obj *DomainEventPublish) TakeChanges() map[string]interface{} {
	if obj.changes == nil {
		return nil
	}
	result := make(map[string]interface{})
	for k, v := range obj.changes {
		result[k] = v
	}
	obj.changes = nil
	return result
}

// updateChanges .
func (obj *DomainEventPublish) setChanges(name string, value interface{}) {
	if obj.changes == nil {
		obj.changes = make(map[string]interface{})
	}
	obj.changes[name] = value
}

// SetTopic .
func (obj *DomainEventPublish) SetTopic(topic string) {
	obj.Topic = topic
	obj.setChanges("topic", topic)
}

// SetSend .
func (obj *DomainEventPublish) SetSend(send int) {
	obj.Send = send
	obj.setChanges("send", send)
}

// SetContent .
func (obj *DomainEventPublish) SetContent(content string) {
	obj.Content = content
	obj.setChanges("content", content)
}

// SetCreated .
func (obj *DomainEventPublish) SetCreated(created time.Time) {
	obj.Created = created
	obj.setChanges("created", created)
}

// SetUpdated .
func (obj *DomainEventPublish) SetUpdated(updated time.Time) {
	obj.Updated = updated
	obj.setChanges("updated", updated)
}

// AddSend .
func (obj *DomainEventPublish) AddSend(send int) {
	obj.Send += send
	obj.setChanges("send", gorm.Expr("send + ?", send))
}
